a = input()
b = a.split(' ')
print((int(b[0]) + int(b[1])) % int(b[2]))
print((int(b[0]) % int(b[2]) + int(b[1]) % int(b[2]) ) % int(b[2]))
print((int(b[0]) * int(b[1])) % int(b[2]))
print((int(b[0]) % int(b[2]) * int(b[1]) % int(b[2]) ) % int(b[2]))